### ISSUE TITLE
Content issue on lecture03 - O-Notation

### ISSUE THREAD

**Issue by neumantm** [trini148/AuB17-18#10]
At the top of lecture03 there is a list of the various O-Notations. I think you mixed up o(n) with O(n) and forgot the real O(n).
Because as I know it is defined as follows:

O(n2 ): Menge aller Funktionen die (asymptotisch) nicht schneller als n2 wachsen(≤).
o(n2 ): Menge aller Funktionen die (asymptotisch) echt langsamer als n2 wachsen(<).
Ω(n2 ): Menge aller Funktionen die (asymptotisch) mind. so schnell wie n2 wachsen(≥).
ω(n2 ): Menge aller Funktionen die (asymptotisch) echt schneller wie n2 wachsen(>).
Θ(n2 ): Menge aller Funktionen die (asymptotisch) genau so schnell wie n2 wachsen(=).

**Comment by trin94** [comment]
Thank you!
I will fix this with the rework of lecture03.

Regards
