### ISSUE TITLE
Content issue on lecture04 - Zero Knowledge Proof

### ISSUE THREAD

**Issue by neumantm** [trini148/AuB17-18#11]
In lecture04 on page 5 line 3 there is the following sentence:
"Falls nun Alice das Geheimnis Φ kennt, so kann sie immer Φ bzw. Φ ◦ π zurückgeben."
But I think it needs to be:
"Falls nun Alice das Geheimnis Φ kennt, so kann sie immer π bzw. Φ ◦ π zurückgeben."
Because it would not be zero knowledge if Alice would return Φ (the secret). And also if she used G2 to create H with π and Bob wants to know the permutation to get from G2 to H, Alice clearly needs to return π.

**Comment by trin94** [comment]
You're right, I will fix it immediately.

Thank you
