### ISSUE TITLE
lecture07 - Definition Hashing

### ISSUE THREAD

**Issue by trin94** [trini148/AuB17-18#15]
Hallo,

aktuell haben wir die folgende Definition des Hashings:
![aub_hashing01](https://user-images.githubusercontent.com/12988790/36641886-80d7904a-1a37-11e8-8ef4-286bde95d60e.png)

Im Mitschrieb vom Vorjahr (https://github.com/dipdi/aub-skript/blob/master/AuB-Skript.pdf)
war es aber folgendermaßen definiert:
![aub_hashing02](https://user-images.githubusercontent.com/12988790/36641879-63131b42-1a37-11e8-8b91-373baf8e00e6.png)

Was stimmt denn nun? Ich hatte mir damals ziemlich sicher die erste Variante notiert. Aber meine Aufschriebe habe ich nicht mehr xD

Gruß

**Comment by FabioSchmidberger** [comment]
also in meiner Doku (https://doku.gitlab.io/docs-software-engineering/doc/datastructures_algorithms/aob/hashing/introduction/introduction.html#definition) hab ich da das gleiche wie du. Ich hab auch nochmal in der commit history nachgeschaut, und da kam der Abschnitt direkt vom mittippen aus der Vorlesung.

**Comment by a-m-w-8** [comment]
Ich meine mich an die n/m Variante zu erinnern! Aber am besten wäre es wohl wenn jemand direkt zum Prof geht und fragt das wäre wohl die einzig verlässliche Quelle :)

**Comment by Dominik8394** [comment]
Es ist meines Wissens nach die letzte Variante mit [...] n/m. Da n/m den Belegungsfaktor bzw. die durchschnittliche Anzahl an zu hashenden Element beschreibt. N/2 ergibt keinen Sinn. Der Belegungsfaktor ist nämlich der Schwellenwert, nachdem man sich richtet (oder richten kann) ab wann ein Hashtafel neu ge-hashed wird. So meine Info :) Man darf mich aber gerne eines besseren belehren falls meine Infos falsch sein sollten.

**Comment by trin94** [comment]
Danke an alle!

Ich hatte die `n/m` Variante damals in das Skript eingefügt und würde es jetzt auch dabei belassen. Falls noch Diskussionsbedarf besteht, kann das Issue ja noch mal geöffnet werden.

Grüße
