### ISSUE TITLE
Lecture 7 - Definition of Hashing

### ISSUE THREAD

**Issue by Dominik8394** [trini148/AuB17-18#17]
Hashing setzt formal voraus, dass wir ein (großes) Universum U haben und eine Schlüsselmenge S als Teilmenge des Universums. Anschließend ist eine Funktion (die Hashfunktion) also eine Abbildung 
h: U -> {0, ... m-1} gesucht. 

Nun zu meiner Frage: In dem vorliegenden Skript fehlt allerdings die Definition von m. Die Zahl m beschreibt meines Wissens nach die Größe der Datenstruktur (Hashtafel) auf welche h die Schlüsselmenge abbildet. Müsste dann das m nicht auch in der vorliegenden Definition enthalten sein?

**Comment by trin94** [comment]
Du hast recht.

Die Definition im Skript entspricht nur dem, was ich von der Tafel habe abschreiben können; ich habe es also entweder vergessen oder es stand nicht an der Tafel.  

Im Skript vom Vorjahr https://github.com/dipdi/aub-skript/blob/master/Vorlesung06.md ist `m` auch in der Definition enthalten. Allerdings stand letztes Jahr sowieso etwas anderes an der Tafel: #15.

**Comment by Dominik8394** [comment]
Okay sehr gut! 

Dankeschön für die Bestätigung! :)
