### ISSUE TITLE
Lecture 6 Skiplisten Pfeile

### ISSUE THREAD

**Issue by FabioSchmidberger** [trini148/AuB17-18#4]
Alle Elemente der Skipliste müssten doch auf unterster Ebene einen Pointer zum nächsten Element nach rechts haben oder?

**Comment by trin94** [comment]
Hey, danke für den Hinweis. 
Du musst recht haben, denn sonst könnte man ja das Element _15_ gar nicht besuchen ...
Ich hatte es vermutlich falsch abgeschrieben.
"Fix" kommt dieses Wochenende.

Gruß
